services:
  - type: web
    name: og-ai-inference-calculator
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
